export const CATE_SELECTION_DROPDOWN = [
    {
        cate: "Tour",
        list: [
            "Tour trong ngày",
            "Tour đi thuyền",
            "Hop on hop off",
            "Tour ẩm thực",
            "Trải nghiệm trên không",
            "Tour nhiều ngày",
            "Đi bộ leo núi",
            "Tour mua sắm",
        ],
    },
    {
        cate: "Du thuyền",
        list: ["Du thuyền trên biển", "Du thuyền ngắm cảnh"],
    },
    {
        cate: "Massage & Suối nước nóng",
        list: ["Spa & Massage", "Suối nước nóng"],
    },
    {
        cate: "Hoạt động dưới nước",
        list: [
            "Lặn ống thở & Lặn bình dưỡng khí",
            "Chèo bè",
            "Chèo ván",
            "Thuê thuyền",
            "Thể thao dưới nước",
            "Chèo kayak",
            "Lướt sóng",
            "Câu cá",
            "Lặn bình dưỡng khí",
            "Vé bãi biển/resort",
        ],
    },
    {
        cate: "Phiêu lưu & Khám phá thiên nhiên",
        list: [
            "Nhảy dù",
            "Nhảy bungee",
            "Leo núi",
            "Trượt zipline",
            "Dù lượn",
            "Xe ATV & Xe AWD",
            "Xe đua go-kart",
            "Xe máy",
            "Golf",
            "Khám phá thiên nhiên",
            "Vượt thác",
            "Cắm trại",
        ],
    },
    {
        cate: "Trải nghiệm văn hoá",
        list: [
            "Workshop",
            "Buổi học nấu ăn",
            "Thử trang phục bản xứ",
            "Chụp ảnh",
            "Salon & Làm đẹp",
        ],
    },
];

export const LANG_SELECTION_DROPDOWN = [
    "Hướng dẫn tiếng Việt",
    "Hướng dẫn tiếng Anh",
    "Hướng dẫn tiếng Trung",
    'Hướng dẫn tiếng Nhật',
    'Hướng dẫn tiếng Hàn'
];

export const TOUR_LIST = [
    {
        img: "/img/tour/recommended-tour-1.webp",
        title: "Tour Tham Quan Vũng Tàu Trong Ngày Khởi Hành Từ Thành Phố Hồ Chí Minh",
        rating: "4.7",
        numRating: "217",
        price: "866.500 VND",
    },
    {
        img: "/img/tour/recommended-tour-2.webp",
        title: "Tour đi bộ tham quan Bảo tàng Chứng tích chiến tranh và Dinh Độc Lập",
        rating: "4.8",
        numRating: "2.3K+",
        price: "450.500 VND",
    },
    {
        img: "/img/tour/recommended-tour-3.webp",
        title: "Địa đạo Củ Chi và Mỹ Tho - Tour 1 ngày TNK",
        rating: "4.5",
        numRating: "2.2K+",
        price: "900.500 VND",
    },
    {
        img: "/img/tour/recommended-tour-4.webp",
        title: "Tour trọn gói Singapore và Malaysia (Gardens by the Bay, Tháp đôi, Cao nguyên Genting, Malacca) - 4N3Đ",
        rating: "4.8",
        numRating: "312",
        price: "7.500.000 VND",
    },
    {
        img: "/img/tour/recommended-tour-5.webp",
        title: "Tour Thái Lan trọn gói (Bangkok, Pattaya) - 5N4Đ",
        rating: "4.5",
        numRating: "123",
        price: "4.978.300 VND",
    },
    {
        img: "/img/tour/boat-tour-1.webp",
        title: "Tour 3N2Đ Đi Thuyền Ngắm Cảnh Komodo từ Labuan Bajo của Sailnesia",
        rating: "4.4",
        numRating: "21",
        price: "7.211.000 VND",
    },
    {
        img: "/img/tour/boat-tour-2.webp",
        title: "Tour Đi Thuyền Ngắm Đảo Rottnest từ Perth hoặc Fremantle",
        rating: "4.3",
        numRating: "22",
        price: "2.750.000 VND",
    },
    {
        img: "/img/tour/boat-tour-3.webp",
        title: "Tour Đi Thuyền Trên Sông Mae Ping Ở Chiang Mai",
        rating: "4.5",
        numRating: "77",
        price: "500.000 VND",
    },
    {
        img: "/img/tour/boat-tour-4.webp",
        title: "Từ Koh Chang: Tour Lặn ống thở & Bãi biển 3/4 Đảo bằng Tàu lớn",
        rating: "4.8",
        numRating: "10",
        price: "758.888 VND",
    },
    {
        img: "/img/tour/boat-tour-5.webp",
        title: "Tour Du Thuyền Ngắm Cá Voi Ở Vịnh Jervis",
        rating: "4.7",
        numRating: "33",
        price: "1.234.589 VND",
    },
    {
        img: "/img/tour/spa-1.webp",
        title: "Trải Nghiệm Tắm Bùn Và Massage Tại Galina Hotel & Spa",
        rating: "4.7",
        numRating: "35",
        price: "212.589 VND",
    },
    {
        img: "/img/tour/spa-2.webp",
        title: "Hà Nội Onsen, Jjimjilbang & Trị liệu Spa | AMARE",
        rating: "4.5",
        numRating: "24",
        price: "370.213 VND",
    },
    {
        img: "/img/tour/spa-3.webp",
        title: "Trải Nghiệm Spa La Maison",
        rating: "4.8",
        numRating: "12",
        price: "350.000 VND",
    },
    {
        img: "/img/tour/spa-4.webp",
        title: "Dịch vụ mát-xa và chăm sóc da mặt tại Charm Spa",
        rating: "4.6",
        numRating: "50",
        price: "380.013 VND",
    },
    {
        img: "/img/tour/spa-5.webp",
        title: "Heaven Spa Lê Nguyễn Nha Trang Kinh nghiệm: Massage chân & toàn thân, Gội dưỡng tóc, Châm cứu trị liệu bằng Laser đặc trưng",
        rating: "4.3",
        numRating: "10",
        price: "150.067 VND",
    },
];
