import localFont from "next/font/local";
import "./globals.css";
import MainHeader from "./components/MainHeader";
import Footer from "./components/Footer";

const poppins = localFont({
    src: [
        {
            path: "./fonts/FZ Poppins-Regular.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "./fonts/FZ Poppins-Italic.ttf",
            weight: "400",
            style: "italic",
        },
        {
            path: "./fonts/FZ Poppins-Medium.ttf",
            weight: "500",
            style: "normal",
        },
        {
            path: "./fonts/FZ Poppins-MediumItalic.ttf",
            weight: "500",
            style: "italic",
        },
        {
            path: "./fonts/FZ Poppins-SemiBold.ttf",
            weight: "600",
            style: "normal",
        },
        {
            path: "./fonts/FZ Poppins-SemiBoldItalic.ttf",
            weight: "600",
            style: "italic",
        },
        {
            path: "./fonts/FZ Poppins-Bold.ttf",
            weight: "700",
            style: "normal",
        },
        {
            path: "./fonts/FZ Poppins-BoldItalic.ttf",
            weight: "700",
            style: "italic",
        },
    ],
});

export const metadata = {
    title: "Vagabond",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${poppins.className}`}>
                <MainHeader></MainHeader>
                <div className="flex-1">{children}</div>
                <Footer></Footer>
            </body>
        </html>
    );
}
