import { Inter } from 'next/font/google'
import "./globals.css";
import MainHeader from "./components/MainHeader";
import Footer from "./components/Footer";


const inter = Inter({ subsets: ['vietnamese'] })

export const metadata = {
    title: "Vagabond",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <MainHeader></MainHeader>
                <div className="flex-1">{children}</div>
                <Footer></Footer>
            </body>
        </html>
    );
}
